export const NAVIGATION = {
  CHANGE_ACTIVE_PATH: 'NAVIGATION.CHANGE_ACTIVE_PATH',
  SET_PAGE_LOADING: 'SET_PAGE_LOADING',
};

export const AUTH = {
  SET_DATA: 'AUTH.SET_DATA',
};

export const LOGIN = {
  SUCCESS: 'LOGIN.SUCCESS',
  LOADING: 'LOGIN.LOADING',
  RESET: 'LOGIN.RESET',
  FAIL: 'LOGIN.FAIL',
};

export const SIGNUP = {
  SUCCESS: 'SIGNUP.SUCCESS',
  LOADING: 'SIGNUP.LOADING',
  RESET: 'SIGNUP.RESET',
  FAIL: 'SIGNUP.FAIL',
};

export const SUBMIT_LOGIN = {
  SUCCESS: 'SUBMIT_LOGIN.SUCCESS',
  LOADING: 'SUBMIT_LOGIN.LOADING',
  FAIL: 'SUBMIT_LOGIN.FAIL',
};

export const PGP_CONFIRM = {
  SUCCESS: 'PGP_CONFIRM.SUCCESS',
  LOADING: 'PGP_CONFIRM.LOADING',
  FAIL: 'PGP_CONFIRM.FAIL',
  SET_DATA: 'PGP_CONFIRM.SET_DATA',
};

export const RECOVERY_ACCOUNT_RESET = {
  SUCCESS: 'RECOVERY_ACCOUNT_RESET.SUCCESS',
  LOADING: 'RECOVERY_ACCOUNT_RESET.LOADING',
  FAIL: 'RECOVERY_ACCOUNT_RESET.FAIL',
  SET_DATA: 'RECOVERY_ACCOUNT_RESET.SET_DATA',
};

export const RECOVERY_ACCOUNT_UPDATE = {
  SUCCESS: 'RECOVERY_ACCOUNT_UPDATE.SUCCESS',
  LOADING: 'RECOVERY_ACCOUNT_UPDATE.LOADING',
  FAIL: 'RECOVERY_ACCOUNT_UPDATE.FAIL',
};

export const SETTINGS_UPDATE_EMAIL = {
  SUCCESS: 'SETTINGS_UPDATE_EMAIL.SUCCESS',
  LOADING: 'SETTINGS_UPDATE_EMAIL.LOADING',
  FAIL: 'SETTINGS_UPDATE_EMAIL.FAIL',
};

export const SETTINGS_UPDATE_PASSWORD = {
  SUCCESS: 'SETTINGS_UPDATE_PASSWORD.SUCCESS',
  LOADING: 'SETTINGS_UPDATE_PASSWORD.LOADING',
  FAIL: 'SETTINGS_UPDATE_PASSWORD.FAIL',
};

export const SETTINGS_UPDATE_PGP = {
  SUCCESS: 'SETTINGS_UPDATE_PGP.SUCCESS',
  LOADING: 'SETTINGS_UPDATE_PGP.LOADING',
  FAIL: 'SETTINGS_UPDATE_PGP.FAIL',
};

export const USER_ITEM = {
  GET_START: 'USER_ITEM.GET_START',
  GET_SUCCESS: 'USER_ITEM.GET_SUCCESS',
  GET_ERROR: 'USER_ITEM.GET_ERROR',
};

export const ACCOUNT_INFO = {
  SUCCESS: 'ACCOUNT_INFO.SUCCESS',
  LOADING: 'ACCOUNT_INFO.LOADING',
  FAIL: 'ACCOUNT_INFO.FAIL',
  SET_DATA: 'ACCOUNT_INFO.SET_DATA',
};

export const CAPTCHA = {
  SUCCESS: 'CAPTCHA.SUCCESS',
  FAIL: 'CAPTCHA.FAIL',
  LOADING: 'CAPTCHA.LOADING',
};

export const PAYMENT_BITCOIN_ADDRESS = {
  SUCCESS: 'ACCOUNT_INFO.SUCCESS',
  LOADING: 'ACCOUNT_INFO.LOADING',
  FAIL: 'ACCOUNT_INFO.FAIL',
  SET_DATA: 'ACCOUNT_INFO.SET_DATA',
};

export const ACCOUNT_BALANCE = {
  SUCCESS: 'ACCOUNT_INFO.SUCCESS',
  LOADING: 'ACCOUNT_INFO.LOADING',
  FAIL: 'ACCOUNT_INFO.FAIL',
  SET_DATA: 'ACCOUNT_INFO.SET_DATA',
};
