export const APP_PAGE_ID = 'APP_ID';

export const FORM_NAMES = {
  LOGIN: 'LOGIN_FORM',
  SINGUP: 'SINGUP_FORM',
  RECOVERY_ACCOUNT_RESET: 'RECOVERY_ACCOUNT_RESET_FORM',
  PGP_CONFIRM: 'PGP_CONFIRM_FORM',
  RECOVERY_ACCOUNT_UPDATE: 'RECOVERY_ACCOUNT_UPDATE_FORM',
  SETTINGS_UPDATE_PASSWORD: 'SETTINGS_UPDATE_PASSWORD_FORM',
  SETTINGS_UPDATE_EMAIL: 'SETTINGS_UPDATE_EMAIL_FORM',
  SETTINGS_UPDATE_PGP: 'SETTINGS_UPDATE_PGP_FORM',
};

export const COOKIE_AUTH = 'COOKIE_AUTH_APP';
